# Generated by Django 4.2.21 on 2025-12-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('profissao', models.CharField(max_length=50)),
                ('credito', models.IntegerField(default=0)),
                ('senha_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
    ]
