# Generated by Django 5.2.8 on 2025-11-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.IntegerField()),
                ('tipo_persona', models.CharField(max_length=50)),
                ('link3D', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('profissao', models.CharField(max_length=50)),
                ('credito', models.IntegerField()),
                ('senha_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_adm', models.CharField(max_length=50)),
                ('senha_adm', models.CharField(max_length=50)),
                ('email_adm', models.EmailField(max_length=100)),
                ('servidor', models.BooleanField()),
                ('credito_add', models.IntegerField()),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='dados.usuario')),
            ],
        ),
    ]
