# Generated by Django 6.0 on 2025-12-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('material', models.CharField(max_length=50)),
                ('dimensoes', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.IntegerField()),
                ('tipo_persona', models.CharField(max_length=50)),
                ('link3D', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligado', models.BooleanField()),
                ('credito_add', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('persona', models.TextField(blank=True, null=True)),
                ('avaliacao', models.TextField(blank=True, null=True)),
                ('estrelas', models.IntegerField(blank=True, null=True)),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='usuarios.usuario')),
                ('FK_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_pedi', to='dados.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_produto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('FK_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_img', to='dados.produto')),
            ],
        ),
    ]
