# Generated by Django 5.2.8 on 2025-11-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('material', models.CharField(max_length=50)),
                ('dimensoes', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.IntegerField()),
                ('tipo_persona', models.CharField(max_length=50)),
                ('link3D', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligado', models.BooleanField()),
                ('credito_add', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('profissao', models.CharField(max_length=50)),
                ('credito', models.IntegerField()),
                ('senha_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
                ('ADM', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_produto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('FK_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_img', to='dados.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('persona', models.TextField(blank=True, null=True)),
                ('avaliacao', models.TextField(blank=True, null=True)),
                ('estrelas', models.IntegerField()),
                ('FK_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_pedi', to='dados.produto')),
                ('FK_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='dados.usuario')),
            ],
        ),
    ]
