# Generated by Django 5.2.3 on 2025-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estrelas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
