# Generated by Django 4.2.27 on 2025-12-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='FK_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='usuarios.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
