# Generated by Django 5.2.8 on 2025-11-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
