# Generated by Django 6.0 on 2025-12-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_alter_pedido_estrelas'),
        ('dados', '0002_alter_pedido_fk_user_delete_usuario'),
    ]

    operations = [
    ]
